import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Hero from '@/components/Hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cabinet Dentaire Ennasr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link key="icon" rel="icon" href="/favicon.ico" />
        <link key="googleFont" rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link key="googleFont2" rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link key="alata" href="https://fonts.googleapis.com/css2?family=Alata&display=swap" rel="stylesheet"></link>
      </Head>
      <Header />
      <main className='max-w-screen-2xl md:px-4 mx-auto'>
        {/************ Hero section ************/}
        <section id="hero">
          <Hero />
        </section>
      </main>
    </>
  )
}
