import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Hero from '@/components/index/Hero'
import Services from '@/components/index/Services'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cabinet Dentaire Ennasr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link key="icon" rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='max-w-screen-2xl md:px-4 mx-auto'>
        {/************ Hero section ************/}
        <section id="hero">
          <Hero />
        </section>
        {/* <div className='h-[1px] w-[85%] mx-auto bg-slate-700/30 my-8'></div> */}
        <section id="services" className='bg-slate-100/40'>
          <Services />
        </section>
      </main>
    </>
  )
}
